import "../styles/globals.scss"    
import Footer from "../../components/Footer";
import { Inter } from 'next/font/google';
import BlogHero from '@/components/blog/BlogHero';
import NextArticlesRow from '@/components/blog/NextArticlesRow';
import Nav from '@/components/Nav';
//import React { useEffect, useState } from 'react';
import {db, subscribeToBlogPosts } from '../firebase';
import { AuthContext, AuthProvider } from '../AuthContext';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
   return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css" />
      </head>
      <AuthProvider>
          <body className={inter.className}>
            {children}
            <NextArticlesRow  />
          </body>
    </AuthProvider>
  
    </html>
  );
}


  // const [name, setName] = useState('');
  // const [profilePic, setProfilePic] = useState('');
  // const [postList, setPostList] = useState([]);

  // useEffect(() => {
  //   // Retrieve data from local storage
  //   const storedName = localStorage.getItem('name');
  //   const storedProfilePic = localStorage.getItem('profilePic');

  //   // Update state if data exists in local storage
  //   if (storedName) {
  //     setName(storedName);
  //   }
  //   if (storedProfilePic) {
  //     setProfilePic(storedProfilePic);
  //   }
  // }, []);

  // useEffect(() => {
  //   const unsubscribe = subscribeToBlogPosts(db, setPostList);

  //   return () => {
  //     unsubscribe(); // Unsubscribe from the snapshot listener
  //   };
  // }, []);
